# Create integration settings
[create]
	# Show train tracks on the atlas map
	# default: true
	showTracks = true
	# Show trains on the atlas map
	# default: true
	showTrains = true
	# Show stations on the atlas map
	# default: true
	showStations = true

# Sable integration settings
[sable]
	# Show ships on the atlas map
	# default: true
	showShips = true
	# Automatically show all ships without manual marking
	# default: false
	autoShowAllShips = false
	# Show altitude in the ship tooltip
	# default: true
	showShipHeight = true
	# Show last seen time in the ship tooltip
	# default: true
	showLastSeen = true

# Simulated integration settings
[simulated]
	# Auto-save nameplate names to ships
	# default: true
	preferNameplateNames = true
